import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.root}>
      <Head>
        <title>Kroth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.layout}>
        <header className={styles.header}>
          <nav className = {styles.navbar}>
            <ul>
              <li><a href={'#'}>About Me</a></li>
              <li><a href={'#'}>Projects</a></li>
              <li><a href={'#'}>Contact</a></li>
            </ul>
          </nav>
        </header>
        <div className={styles.content}>
          <main>
            
          </main>
        </div>
      </div>
    </div>
  )
}

export default Home
