
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import test1 from '../public/test1.jpg'
import React from 'react'
import NavBar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div className={styles.root}>
      <Head>
        <title>Kroth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.layout}>
        <NavBar/>
        <div className={styles.content}>
          <main>
            <section className={styles.main}>
              <div className={styles.mainText}>
                <h1>
                  <p className={styles.salution}> Hello there, my name is</p>
                  <p className={styles.name}>Luiz Kroth.</p>
                  <p className={styles.work}> I ‘m a Software Engineer Student.</p>
                  <p className={styles.who}>I’m a brazilian software engineer student, mostly focused on front-end web development.</p>
                </h1>
              </div>
            </section>
            <section className={styles.AboutMe} id='AboutMe'>
              <div className={styles.Resume}>
                <div className={styles.AboutPicture}>
                  <Image src={test1} className={styles.ProfilePic}></Image>
                </div>
                <span className={styles.AboutHead}>About Me</span>
                <hr></hr>
                <div className={styles.AboutText}>
                  <p>
                    Greetings! My name is Luiz and I'm a 20 years old software engineer student at Univates,
                    I began learning how to code in the first half of 2020, when i joined Univates.
                    The first coding language I learned there was Java, where I gained an understanding
                    of variables, loops, arrays, classes, inheritance, ... 
                  </p>
                  {/* mudar o texto de baixo ta mt ruim */}
                  <p>  
                    Later on that year I started learning by my self Javascript, HTML, CSS, but mostly NodeJS, my 
                    first personal project was a Discord Chat Bot which purpose was to help server management, 
                    and it also had some fun interactions in certain commands. Turned out that i learned a lot
                    while building it.
                  </p>
                  <p>
                    Some languages and frameworks that I'm currently using/learning:
                  </p>
                  <ul className={styles.TechSkills}>
                    <li>JavaScript</li>
                    <li>TypeScript</li>
                    <li>Next.Js</li>
                    <li>React</li>
                    <li>Python</li>
                    <li>PostgreSQL</li>
                  </ul>
                </div>
              </div>
            </section>
          </main>
        </div>
      </div>
    </div>
  )
};

export default Home
