
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import test1 from '../public/test1.jpg'
import p1 from '../public/p1.png'
import React from 'react'
import NavBar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div className={styles.root}>
      <Head>
        <title>Kroth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div className={styles.layout}>
        <NavBar/>
        <div className={styles.content}>
          <main>
            <section className={styles.main}>
              <div className={styles.mainText}>
                <h1>
                  <p className={styles.salution}> Hello there, my name is</p>
                  <p className={styles.name}>Luiz Kroth.</p>
                  <p className={styles.work}> I ‘m a Software Engineer Student.</p>
                  <p className={styles.who}>I’m a brazilian software engineer student at Univates.</p>
                </h1>
              </div>
            </section>
            <section className={styles.AboutMe} id='AboutMe'>
              <div className={styles.Resume}>
                <div className={styles.AboutPicture}>
                  <Image src={test1} className={styles.ProfilePic}></Image>
                </div>
                <span className={styles.AboutHead}>About Me</span>
                <hr></hr>
                <div className={styles.AboutText}>
                  <p>
                    Greetings! My name is Luiz and I'm a 20 years old software engineer student at
                    <a className={styles.highlight} href='https://www.univates.br/' target='_blank'> Univates</a>,
                    I began learning how to code in the first half of 2020, when i joined Univates.
                    The first coding language I learned there was Java, where I gained an understanding
                    of variables, loops, arrays, classes, inheritance, ... 
                  </p>
                  <p>  
                    I started studying JavaScript, HTML and CSS by my own in the middle of 2021, now I'm 
                    mostly focused in learning TypeScript, in fact this whole portfolio it was made using TypeScript 
                    and Next.Js, its also full responsive. <span className={styles.highlight}>At the moment I'm looking 
                    forward to get an internship so I can improve and gain more experience from it.</span>
                  </p>
                  <p>
                    Some languages and frameworks that I'm currently using/learning:
                  </p>
                  <ul className={styles.TechSkills}>
                    <li>TypeScript</li>
                    <li>Java</li>
                    <li>Next.Js</li>
                    <li>React</li>
                    <li>Python</li>
                    <li>PostgreSQL</li>
                  </ul>
                </div>
              </div>
            </section>
            <section className={styles.Projects} id='Projects'>
              <hr></hr>
              {/* se esqueceu de botar o titulo da secao */}
              <div className={styles.ProjectsField}>
                <div className={styles.Project}>
                  <Image src={p1} className={styles.ProjectI}></Image>
                  <span className={styles.ProjectTitle}>Portfolio-v1</span>
                </div>
              </div>
            </section>
            <section className={styles.Contact} id='Contact'>

            </section>
          </main>
        </div>
        <footer></footer>
      </div>
    </div>
  )
};

export default Home
